version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build'
      include: scope
  - package-ecosystem: 'npm'
    directory: '/packages/cli'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build'
      include: scope
  - package-ecosystem: 'npm'
    directory: '/packages/web'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build'
      include: scope
